-- MySQL Script generated by MySQL Workbench
-- 02/18/18 22:41:57
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema addwork
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema addwork
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `addwork` ;
USE `addwork` ;

-- -----------------------------------------------------
-- Table `addwork`.`works`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `addwork`.`works` (
  `id_works` INT NOT NULL AUTO_INCREMENT,
  `workname` VARCHAR(50) NOT NULL,
  `cost_day` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id_works`),
  INDEX `type_id_UNIQUE` (`id_works` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `addwork`.`clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `addwork`.`clients` (
  `id_client` INT NOT NULL AUTO_INCREMENT,
  `client_name` VARCHAR(45) NOT NULL,
  `telephone` BIGINT(12) NOT NULL,
  `cash` DECIMAL(10,2) NOT NULL,
  `adress` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_client`),
  INDEX `type_id_client_UNIQUE` (`id_client` ASC),
  INDEX `type_name_client_UNIQUE` (`client_name` ASC),
  CONSTRAINT `work_key`
    FOREIGN KEY (`id_client`)
    REFERENCES `addwork`.`works` (`id_works`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `addwork`.`dates`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `addwork`.`dates` (
  `id_value` INT NOT NULL AUTO_INCREMENT,
  `date_begin` DATETIME NOT NULL,
  `date_end` DATETIME NOT NULL,
  PRIMARY KEY (`id_value`),
  INDEX `type_id_date_UNIQUE` (`id_value` ASC),
  CONSTRAINT `fk_id`
    FOREIGN KEY (`id_value`)
    REFERENCES `addwork`.`works` (`id_works`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
