-- MySQL Script generated by MySQL Workbench
-- 03/24/18 23:26:57
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema addwork
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema addwork
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `addwork` ;
USE `addwork` ;

-- -----------------------------------------------------
-- Table `addwork`.`works`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `addwork`.`works` (
  `id_works` INT NOT NULL AUTO_INCREMENT,
  `workname` VARCHAR(50) NOT NULL,
  `cost_day` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id_works`),
  INDEX `type_id_UNIQUE` (`id_works` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `addwork`.`employees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `addwork`.`employees` (
  `id_employ` INT NOT NULL AUTO_INCREMENT,
  `employee_name` VARCHAR(45) NOT NULL,
  `telephone` BIGINT(12) NOT NULL,
  `cash` DECIMAL(10,2) NOT NULL,
  `adress` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_employ`),
  INDEX `type_id_employ_UNIQUE` (`id_employ` ASC),
  INDEX `type_name_employ_UNIQUE` (`employee_name` ASC),
  CONSTRAINT `work_key`
    FOREIGN KEY (`id_employ`)
    REFERENCES `addwork`.`works` (`id_works`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `addwork`.`dates`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `addwork`.`dates` (
  `id_value` INT NOT NULL AUTO_INCREMENT,
  `date_begin` DATETIME NOT NULL,
  `date_end` DATETIME NOT NULL,
  PRIMARY KEY (`id_value`),
  INDEX `type_id_date_UNIQUE` (`id_value` ASC),
  CONSTRAINT `fk_id`
    FOREIGN KEY (`id_value`)
    REFERENCES `addwork`.`works` (`id_works`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `addwork`.`rework`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `addwork`.`rework` (
  `id_rework` INT NOT NULL,
  `rework` VARCHAR(45) NOT NULL,
  `number_employees` INT NOT NULL,
  `time_start` DATETIME NOT NULL,
  `time_finish` DATETIME NOT NULL,
  PRIMARY KEY (`id_rework`),
  INDEX `id` (`id_rework` ASC),
  INDEX `rework` (`rework` ASC),
  INDEX `fk_work_UNIQUE_idx` (`number_employees` ASC),
  CONSTRAINT `fk_id_rework_UNIQUE`
    FOREIGN KEY (`id_rework`)
    REFERENCES `addwork`.`works` (`id_works`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_work_UNIQUE`
    FOREIGN KEY (`number_employees`)
    REFERENCES `addwork`.`employees` (`id_employ`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
