-- MySQL Script generated by MySQL Workbench
-- 03/24/18 23:29:31
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema addwork
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema addwork
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `addwork` ;
USE `addwork` ;

-- -----------------------------------------------------
-- Table `addwork`.`works`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `addwork`.`works` (
  `id_works` INT NOT NULL AUTO_INCREMENT,
  `workname` VARCHAR(50) NOT NULL,
  `cost_day` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id_works`),
  INDEX `type_id_UNIQUE` (`id_works` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
