-- MySQL Script generated by MySQL Workbench
-- 03/24/18 23:28:18
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema addwork
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema addwork
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `addwork` ;
USE `addwork` ;

-- -----------------------------------------------------
-- Table `addwork`.`rework`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `addwork`.`rework` (
  `id_rework` INT NOT NULL,
  `rework` VARCHAR(45) NOT NULL,
  `number_employees` INT NOT NULL,
  `time_start` DATETIME NOT NULL,
  `time_finish` DATETIME NOT NULL,
  PRIMARY KEY (`id_rework`),
  INDEX `id` (`id_rework` ASC),
  INDEX `rework` (`rework` ASC),
  INDEX `fk_work_UNIQUE_idx` (`number_employees` ASC),
  CONSTRAINT `fk_id_rework_UNIQUE`
    FOREIGN KEY (`id_rework`)
    REFERENCES `addwork`.`works` (`id_works`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_work_UNIQUE`
    FOREIGN KEY (`number_employees`)
    REFERENCES `addwork`.`employees` (`id_employ`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
