-- MySQL Script generated by MySQL Workbench
-- 03/24/18 23:29:10
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema addwork
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema addwork
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `addwork` ;
USE `addwork` ;

-- -----------------------------------------------------
-- Table `addwork`.`employees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `addwork`.`employees` (
  `id_employ` INT NOT NULL AUTO_INCREMENT,
  `employee_name` VARCHAR(45) NOT NULL,
  `telephone` BIGINT(12) NOT NULL,
  `cash` DECIMAL(10,2) NOT NULL,
  `adress` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_employ`),
  INDEX `type_id_employ_UNIQUE` (`id_employ` ASC),
  INDEX `type_name_employ_UNIQUE` (`employee_name` ASC),
  CONSTRAINT `work_key`
    FOREIGN KEY (`id_employ`)
    REFERENCES `addwork`.`works` (`id_works`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
